name: Tests
on: [push]

jobs:
  lint-test:
    name: Lint + Test
    uses: gsa/data.gov/.github/workflows/ckan-test.yml@ckan-210
    with:
      ext_name: datajson
      plugins: datajson harvest datajson_validator datajson_harvest
    secrets: inherit
